// const Bags = [
//   {
//     id: 1,
//     name: "Premium Wireless Headphones",
//     category: "Electronics",
//     price: "$129.99",
//     originalPrice: "$199.99",
//     discount: "35% OFF",
//     rating: 4.5,
//     reviewCount: 128,
//     imageColor: "bg-gradient-to-r from-blue-400 to-indigo-500",
//     tags: ["Wireless", "Noise Cancelling", "30h Battery"],
//     isNew: true,
//   },
//   {
//     id: 2,
//     name: "Summer Cotton T-Shirt",
//     category: "Fashion",
//     price: "$24.99",
//     originalPrice: "$39.99",
//     discount: "38% OFF",
//     rating: 4.2,
//     reviewCount: 89,
//     imageColor: "bg-gradient-to-r from-pink-400 to-rose-500",
//     tags: ["Cotton", "Comfort Fit"],
//     isNew: false,
//   },
//   {
//     id: 3,
//     name: "Leather Backpack",
//     category: "Bags",
//     price: "$89.99",
//     originalPrice: "$149.99",
//     discount: "40% OFF",
//     rating: 4.7,
//     reviewCount: 203,
//     imageColor: "bg-gradient-to-r from-amber-400 to-orange-500",
//     tags: ["Genuine Leather", "Laptop Sleeve"],
//     isNew: true,
//   },
//   {
//     id: 4,
//     name: "Running Shoes",
//     category: "Footwear",
//     price: "$79.99",
//     originalPrice: "$129.99",
//     discount: "38% OFF",
//     rating: 4.4,
//     reviewCount: 156,
//     imageColor: "bg-gradient-to-r from-emerald-400 to-teal-500",
//     tags: ["Lightweight", "Breathable"],
//     isNew: false,
//   },
//   {
//     id: 5,
//     name: "Smart Watch Series 5",
//     category: "Electronics",
//     price: "$199.99",
//     originalPrice: "$299.99",
//     discount: "33% OFF",
//     rating: 4.6,
//     reviewCount: 312,
//     imageColor: "bg-gradient-to-r from-purple-400 to-violet-500",
//     tags: ["Heart Rate", "Waterproof"],
//     isNew: true,
//   },
//   {
//     id: 6,
//     name: "Organic Face Cream",
//     category: "Beauty",
//     price: "$34.99",
//     originalPrice: "$49.99",
//     discount: "30% OFF",
//     rating: 4.3,
//     reviewCount: 67,
//     imageColor: "bg-gradient-to-r from-green-400 to-lime-500",
//     tags: ["Organic", "Vegan"],
//     isNew: false,
//   },
// ];
// export default Bags;

// // ///////////////////
