// const Cart = [
//   {
//     id: 1,
//     name: "Apple iPhone 14 Pro Max",
//     description: "256GB Deep Purple - Unlocked (Renewed Premium)",
//     price: 999.99,
//     originalPrice: 1199.99,
//     quantity: 1,
//     image:
//       "https://images.unsplash.com/photo-1664478546384-d57ffe74a78c?w=500&auto=format&fit=crop&q=60",
//     inStock: true,
//     isEligibleForFreeShipping: true,
//     isSavedForLater: false,
//     isPrimeEligible: true,
//     deliveryDate: "Tomorrow, Jan 15",
//     seller: "Apple Store",
//     color: "Deep Purple",
//     storage: "256GB",
//     condition: "Renewed Premium",
//     warranty: "1 Year Warranty",
//     maxQuantity: 3,
//   },
//   {
//     id: 2,
//     name: "Sony WH-1000XM5 Wireless Noise Cancelling Headphones",
//     description: "Industry Leading Noise Cancellation, 30-hour Battery Life",
//     price: 349.99,
//     originalPrice: 399.99,
//     quantity: 2,
//     image:
//       "https://images.unsplash.com/photo-1505740420928-5e560c06d30e?w=500&auto=format&fit=crop&q=60",
//     inStock: true,
//     isEligibleForFreeShipping: true,
//     isSavedForLater: false,
//     isPrimeEligible: true,
//     deliveryDate: "Tomorrow, Jan 15",
//     seller: "Sony Official Store",
//     color: "Black",
//     type: "Over-Ear",
//     batteryLife: "30 hours",
//     warranty: "2 Years Warranty",
//     maxQuantity: 5,
//   },
//   {
//     id: 3,
//     name: "Amazon Kindle Paperwhite",
//     description: '8GB, 6.8" Display, Adjustable Warm Light, Waterproof',
//     price: 139.99,
//     originalPrice: 149.99,
//     quantity: 1,
//     image:
//       "https://images.unsplash.com/photo-1544716278-ca5e3f4abd8c?w=500&auto=format&fit=crop&q=60",
//     inStock: true,
//     isEligibleForFreeShipping: true,
//     isSavedForLater: false,
//     isPrimeEligible: false,
//     deliveryDate: "Wednesday, Jan 17",
//     seller: "Amazon",
//     color: "Black",
//     storage: "8GB",
//     screenSize: "6.8 inches",
//     waterproof: true,
//     maxQuantity: 10,
//   },
//   {
//     id: 4,
//     name: "Nike Air Max 270",
//     description: "Men's Running Shoes, Size 10, Black/White",
//     price: 129.99,
//     originalPrice: 159.99,
//     quantity: 1,
//     image:
//       "https://images.unsplash.com/photo-1542291026-7eec264c27ff?w=500&auto=format&fit=crop&q=60",
//     inStock: true,
//     isEligibleForFreeShipping: false,
//     isSavedForLater: true,
//     isPrimeEligible: true,
//     deliveryDate: "Friday, Jan 19",
//     seller: "Nike Store",
//     color: "Black/White",
//     size: "10",
//     style: "Running Shoes",
//     maxQuantity: 2,
//   },
// ];

// export default Cart;
