// // const Electronics = [
// //   {
// //     id: 1,
// //     name: "Premium Wireless Headphones",
// //     category: "Electronics",
// //     price: "$129.99",
// //     originalPrice: "$199.99",
// //     discount: "35% OFF",
// //     rating: 4.5,
// //     reviewCount: 128,
// //     imageColor: "bg-gradient-to-r from-blue-400 to-indigo-500",
// //     tags: ["Wireless", "Noise Cancelling", "30h Battery"],
// //     isNew: true,
// //   },
// //   {
// //     id: 2,
// //     name: "Summer Cotton T-Shirt",
// //     category: "Fashion",
// //     price: "$24.99",
// //     originalPrice: "$39.99",
// //     discount: "38% OFF",
// //     rating: 4.2,
// //     reviewCount: 89,
// //     imageColor: "bg-gradient-to-r from-pink-400 to-rose-500",
// //     tags: ["Cotton", "Comfort Fit"],
// //     isNew: false,
// //   },
// //   {
// //     id: 3,
// //     name: "Leather Backpack",
// //     category: "Bags",
// //     price: "$89.99",
// //     originalPrice: "$149.99",
// //     discount: "40% OFF",
// //     rating: 4.7,
// //     reviewCount: 203,
// //     imageColor: "bg-gradient-to-r from-amber-400 to-orange-500",
// //     tags: ["Genuine Leather", "Laptop Sleeve"],
// //     isNew: true,
// //   },
// //   {
// //     id: 4,
// //     name: "Running Shoes",
// //     category: "Footwear",
// //     price: "$79.99",
// //     originalPrice: "$129.99",
// //     discount: "38% OFF",
// //     rating: 4.4,
// //     reviewCount: 156,
// //     imageColor: "bg-gradient-to-r from-emerald-400 to-teal-500",
// //     tags: ["Lightweight", "Breathable"],
// //     isNew: false,
// //   },
// //   {
// //     id: 5,
// //     name: "Smart Watch Series 5",
// //     category: "Electronics",
// //     price: "$199.99",
// //     originalPrice: "$299.99",
// //     discount: "33% OFF",
// //     rating: 4.6,
// //     reviewCount: 312,
// //     imageColor: "bg-gradient-to-r from-purple-400 to-violet-500",
// //     tags: ["Heart Rate", "Waterproof"],
// //     isNew: true,
// //   },
// //   {
// //     id: 6,
// //     name: "Organic Face Cream",
// //     category: "Beauty",
// //     price: "$34.99",
// //     originalPrice: "$49.99",
// //     discount: "30% OFF",
// //     rating: 4.3,
// //     reviewCount: 67,
// //     imageColor: "bg-gradient-to-r from-green-400 to-lime-500",
// //     tags: ["Organic", "Vegan"],
// //     isNew: false,
// //   },
// // ];
// // export default Electronics;

// const Electronics = [
//   {
//     id: 1,
//     name: "Wireless Noise‑Cancelling Headphones",
//     category: "Electronics",
//     price: "$129.99",
//     originalPrice: "$199.99",
//     discount: "35% OFF",
//     rating: 4.7,
//     reviewCount: 340,
//     image:
//       "https://images.unsplash.com/photo-1580894908361-6ad1d22739b3?auto=format&fit=crop&w=400&q=80",
//     tags: ["Wireless", "Noise Cancelling", "Bluetooth 5.0"],
//     isNew: true,
//   },
//   {
//     id: 2,
//     name: "Smartphone 128GB – Midnight Black",
//     category: "Electronics",
//     price: "$699.99",
//     originalPrice: "$799.99",
//     discount: "12% OFF",
//     rating: 4.5,
//     reviewCount: 580,
//     image:
//       "https://images.unsplash.com/photo-1512499617640-c2f9992c4d91?auto=format&fit=crop&w=400&q=80",
//     tags: ["Smartphone", "128GB", "5G"],
//     isNew: false,
//   },
//   {
//     id: 3,
//     name: "Portable Bluetooth Speaker",
//     category: "Electronics",
//     price: "$49.99",
//     originalPrice: "$79.99",
//     discount: "37% OFF",
//     rating: 4.3,
//     reviewCount: 210,
//     image:
//       "https://images.unsplash.com/photo-1580894894517-9cf7c5f466c1?auto=format&fit=crop&w=400&q=80",
//     tags: ["Bluetooth", "Portable", "Water‑Resistant"],
//     isNew: true,
//   },
//   {
//     id: 4,
//     name: "4K Ultra HD Smart TV – 55 inch",
//     category: "Electronics",
//     price: "$799.99",
//     originalPrice: "$999.99",
//     discount: "20% OFF",
//     rating: 4.6,
//     reviewCount: 430,
//     image:
//       "https://images.unsplash.com/photo-1582213782179-992a9de5138e?auto=format&fit=crop&w=400&q=80",
//     tags: ["4K", "Smart TV", "55 inch"],
//     isNew: false,
//   },
//   {
//     id: 5,
//     name: "Gaming Laptop 16GB RAM / 1TB SSD",
//     category: "Electronics",
//     price: "$1199.99",
//     originalPrice: "$1499.99",
//     discount: "20% OFF",
//     rating: 4.8,
//     reviewCount: 290,
//     image:
//       "https://images.unsplash.com/photo-1587202372775-44d47f91f8b9?auto=format&fit=crop&w=400&q=80",
//     tags: ["Laptop", "16GB RAM", "1TB SSD"],
//     isNew: true,
//   },
//   {
//     id: 6,
//     name: "Smart Watch – Fitness Tracker",
//     category: "Electronics",
//     price: "$199.99",
//     originalPrice: "$249.99",
//     discount: "20% OFF",
//     rating: 4.4,
//     reviewCount: 165,
//     image:
//       "https://images.unsplash.com/photo-1598970434795-0c54fe7c0642?auto=format&fit=crop&w=400&q=80",
//     tags: ["Smart Watch", "Fitness", "Heart‑Rate Monitor"],
//     isNew: false,
//   },
//   {
//     id: 7,
//     name: "Wireless Ergonomic Mouse",
//     category: "Electronics",
//     price: "$29.99",
//     originalPrice: "$49.99",
//     discount: "40% OFF",
//     rating: 4.2,
//     reviewCount: 88,
//     image:
//       "https://images.unsplash.com/photo-1587825140708-3d2fe1eda3d3?auto=format&fit=crop&w=400&q=80",
//     tags: ["Mouse", "Wireless", "Ergonomic"],
//     isNew: true,
//   },
//   {
//     id: 8,
//     name: "Noise‑Cancelling Earbuds",
//     category: "Electronics",
//     price: "$59.99",
//     originalPrice: "$99.99",
//     discount: "40% OFF",
//     rating: 4.3,
//     reviewCount: 240,
//     image:
//       "https://images.unsplash.com/photo-1580894894516-18d58e2033bd?auto=format&fit=crop&w=400&q=80",
//     tags: ["Earbuds", "Noise Cancelling", "Bluetooth"],
//     isNew: false,
//   },
// ];

// export default Electronics;
