// const Fashion = [
//   {
//     id: 1,
//     name: "Urban Streetwear Hoodie",
//     category: "Fashion",
//     price: "$49.99",
//     originalPrice: "$79.99",
//     discount: "38% OFF",
//     rating: 4.6,
//     reviewCount: 210,
//     image:
//       "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcTeS16SUn0YWL8q3jFMkUi4l3r-o_srahadRQ&s",
//     tags: ["Hoodie", "Streetwear", "Unisex"],
//     isNew: true,
//   },
//   {
//     id: 2,
//     name: "Classic Blue Denim Jacket",
//     category: "Fashion",
//     price: "$59.99",
//     originalPrice: "$99.99",
//     discount: "40% OFF",
//     rating: 4.4,
//     reviewCount: 188,
//     image:
//       "https://nobero.com/cdn/shop/files/Black_eef6ff5f-72f5-4562-b31b-18a677952c9a.jpg?v=1763123301",
//     tags: ["Denim", "Casual", "Unisex"],
//     isNew: false,
//   },
//   {
//     id: 3,
//     name: "Premium Leather Handbag",
//     category: "Fashion",
//     price: "$89.99",
//     originalPrice: "$149.99",
//     discount: "42% OFF",
//     rating: 4.8,
//     reviewCount: 345,
//     image: "https://images.unsplash.com/photo-1584917865442-de89df76afd3",
//     tags: ["Handbag", "Leather", "Luxury"],
//     isNew: true,
//   },
//   {
//     id: 4,
//     name: "Minimalist White Sneakers",
//     category: "Fashion",
//     price: "$69.99",
//     originalPrice: "$119.99",
//     discount: "41% OFF",
//     rating: 4.7,
//     reviewCount: 420,
//     image: "https://images.unsplash.com/photo-1526170375885-4d8ecf77b99f",
//     tags: ["Sneakers", "Unisex", "Comfort"],
//     isNew: false,
//   },
//   {
//     id: 5,
//     name: "Elegant Silk Scarf",
//     category: "Fashion",
//     price: "$29.99",
//     originalPrice: "$49.99",
//     discount: "40% OFF",
//     rating: 4.3,
//     reviewCount: 76,
//     image: "https://images.unsplash.com/photo-1618354691373-f354c7985f85",
//     tags: ["Scarf", "Silk", "Luxury"],
//     isNew: true,
//   },
//   {
//     id: 6,
//     name: "Slim Fit Formal Blazer",
//     category: "Fashion",
//     price: "$89.99",
//     originalPrice: "$149.99",
//     discount: "40% OFF",
//     rating: 4.5,
//     reviewCount: 152,
//     image: "https://images.unsplash.com/photo-1602810310473-5a6b9c8f89dd",
//     tags: ["Blazer", "Formal", "Men"],
//     isNew: false,
//   },
//   {
//     id: 7,
//     name: "High-Waist Skinny Jeans",
//     category: "Fashion",
//     price: "$39.99",
//     originalPrice: "$69.99",
//     discount: "43% OFF",
//     rating: 4.2,
//     reviewCount: 98,
//     image: "https://images.unsplash.com/photo-1503342394128-db5f28f7d2dd",
//     tags: ["Jeans", "Women", "Stretchable"],
//     isNew: false,
//   },
//   {
//     id: 8,
//     name: "Luxury Wristwatch – Rose Gold",
//     category: "Fashion",
//     price: "$149.99",
//     originalPrice: "$249.99",
//     discount: "40% OFF",
//     rating: 4.9,
//     reviewCount: 500,
//     image: "https://images.unsplash.com/photo-1518544801958-efcbf8a7ec10",
//     tags: ["Watch", "Luxury", "Unisex"],
//     isNew: true,
//   },
// ];
// export default Fashion;
