// const Footwear = [
//   {
//     id: 1,
//     name: "Men's Running Sneakers",
//     category: "Footwear",
//     price: "$69.99",
//     originalPrice: "$99.99",
//     discount: "30% OFF",
//     rating: 4.5,
//     reviewCount: 320,
//     image:
//       "https://images.unsplash.com/photo-1600185367564-97d53a3fa9f6?auto=format&fit=crop&w=800&q=80",
//     tags: ["Sneakers", "Running", "Men"],
//     isNew: true,
//   },
//   {
//     id: 2,
//     name: "Women's Casual Loafers",
//     category: "Footwear",
//     price: "$59.99",
//     originalPrice: "$89.99",
//     discount: "33% OFF",
//     rating: 4.2,
//     reviewCount: 145,
//     image:
//       "https://images.unsplash.com/photo-1595950656770-8ff8bbd6c6d1?auto=format&fit=crop&w=800&q=80",
//     tags: ["Loafers", "Casual", "Women"],
//     isNew: false,
//   },
//   {
//     id: 3,
//     name: "Unisex Sports Sandals",
//     category: "Footwear",
//     price: "$39.99",
//     originalPrice: "$59.99",
//     discount: "33% OFF",
//     rating: 4.7,
//     reviewCount: 210,
//     image:
//       "https://images.unsplash.com/photo-1600180758893-6f60c2b9ebc6?auto=format&fit=crop&w=800&q=80",
//     tags: ["Sandals", "Sports", "Unisex"],
//     isNew: true,
//   },
//   {
//     id: 4,
//     name: "Leather Formal Shoes",
//     category: "Footwear",
//     price: "$89.99",
//     originalPrice: "$129.99",
//     discount: "31% OFF",
//     rating: 4.6,
//     reviewCount: 185,
//     image:
//       "https://images.unsplash.com/photo-1595950656744-0c8b16bb5b8f?auto=format&fit=crop&w=800&q=80",
//     tags: ["Formal", "Leather", "Men"],
//     isNew: false,
//   },
//   {
//     id: 5,
//     name: "High-Top Canvas Sneakers",
//     category: "Footwear",
//     price: "$54.99",
//     originalPrice: "$79.99",
//     discount: "31% OFF",
//     rating: 4.4,
//     reviewCount: 270,
//     image:
//       "https://images.unsplash.com/photo-1600185367585-446d0ffb3e36?auto=format&fit=crop&w=800&q=80",
//     tags: ["Sneakers", "Canvas", "Unisex"],
//     isNew: true,
//   },
//   {
//     id: 6,
//     name: "Trail Hiking Boots",
//     category: "Footwear",
//     price: "$99.99",
//     originalPrice: "$149.99",
//     discount: "33% OFF",
//     rating: 4.8,
//     reviewCount: 95,
//     image:
//       "https://images.unsplash.com/photo-1600185367560-0b3c5a824c7d?auto=format&fit=crop&w=800&q=80",
//     tags: ["Hiking", "Boots", "Unisex"],
//     isNew: true,
//   },
// ];
// export default Footwear;
